"""baseline_initial_schema

Revision ID: 74d249fd4a23
Revises: 
Create Date: 2026-09-10 11:49:05.810791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74d249fd4a23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_action_logs_report_id'), ['report_id'], unique=False)

    with op.batch_alter_table('connector_configs', schema=None) as batch_op:
        batch_op.alter_column('db_type',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'mysql'"))
        batch_op.alter_column('target_database',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False,
               existing_server_default=sa.text("'glpi_local'"))
        batch_op.alter_column('table_prefix',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False,
               existing_server_default=sa.text("'glpi_'"))

    with op.batch_alter_table('connector_sync_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_table_name'))
        batch_op.create_index(batch_op.f('ix_connector_sync_tables_table_name'), ['table_name'], unique=False)

    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dashboard_sources', ['source_id_b'], ['id'])
        batch_op.create_foreign_key(None, 'dashboards', ['dashboard_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('connector_sync_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_sync_tables_table_name'))
        batch_op.create_index(batch_op.f('idx_table_name'), ['table_name'], unique=False)

    with op.batch_alter_table('connector_configs', schema=None) as batch_op:
        batch_op.alter_column('table_prefix',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True,
               existing_server_default=sa.text("'glpi_'"))
        batch_op.alter_column('target_database',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True,
               existing_server_default=sa.text("'glpi_local'"))
        batch_op.alter_column('db_type',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'mysql'"))

    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_action_logs_report_id'))

    # ### end Alembic commands ###
